const {chromium}=require('C:/Users/an.chauh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const context=await browser.newContext({viewport:{width:375,height:812}});await context.addCookies([{name:'travelplus_locale',value:'vi',url:'http://localhost'}]);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost/',{waitUntil:'networkidle'});const reject=page.getByRole('button',{name:'Từ chối tùy chọn',exact:true});if(await reject.isVisible())await reject.click();
assert.equal(await page.locator('main').count(),1);assert.equal(await page.locator('.home-services-compact__card').count(),3);assert.equal(await page.locator('.home-summer-spotlight').count(),0);
const nav=page.locator('#site-navigation'),open=page.locator('.mobile-menu-btn');assert.equal(await nav.evaluate(e=>e.inert),true);await open.focus();await page.keyboard.press('Enter');assert.equal(await open.getAttribute('aria-expanded'),'true');assert.equal(await page.locator('.menu-close-btn').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Shift+Tab');assert.equal(await nav.evaluate(e=>e.contains(document.activeElement)),true);await page.keyboard.press('Escape');assert.equal(await open.getAttribute('aria-expanded'),'false');assert.equal(await open.evaluate(e=>e===document.activeElement),true);
await open.click();const toggle=nav.locator(':scope > .menu-list > li > .dropdown-icon').first();await toggle.focus();await page.keyboard.press('Enter');assert.equal(await toggle.getAttribute('aria-expanded'),'true');await page.keyboard.press('Space');assert.equal(await toggle.getAttribute('aria-expanded'),'false');await page.keyboard.press('Escape');
await page.locator('.site-skip-link').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'site-main-content');
const pause=page.locator('[data-hero-toggle]');await pause.click();assert.equal(await pause.getAttribute('aria-pressed'),'true');const current=await page.locator('[data-hero-rotator] img.is-active').getAttribute('src');await page.waitForTimeout(7600);assert.equal(await page.locator('[data-hero-rotator] img.is-active').getAttribute('src'),current);await pause.click();await page.waitForTimeout(8500);assert.notEqual(await page.locator('[data-hero-rotator] img.is-active').getAttribute('src'),current);await pause.click();
await page.locator('.home-more-stories > summary').click();assert.equal(await page.locator('.home-more-stories').getAttribute('open'),'');await page.locator('.home-more-stories > summary').click();
for(const width of [320,375,768,1024,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);assert.equal(await nav.evaluate(e=>e.inert),width<1200);}
await page.screenshot({path:'writable/audit-p2-desktop.png',fullPage:true});await page.setViewportSize({width:375,height:812});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'writable/audit-p2-mobile.png'});
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await pause.getAttribute('aria-pressed'),'true');await page.goto('http://localhost/tim-kiem-tour',{waitUntil:'networkidle'});assert.equal(await page.locator('main').count(),1);await page.goto('http://localhost/en',{waitUntil:'networkidle'});assert.equal(await page.locator('[data-hero-toggle]').innerText(),'Play slideshow');assert.equal(await page.locator('.home-services-compact__card').count(),3);assert.deepEqual(errors,[]);console.log('PASS: keyboard menu, focus trap/restore, Escape, submenus, skip link, pause/resume, reduced motion, details, 5 viewport widths, VI/EN, one main landmark, no JS errors');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
