CREATE TABLE IF NOT EXISTS `bookings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `booking_code` VARCHAR(32) NOT NULL,
  `user_id` INT UNSIGNED DEFAULT NULL,
  `tour_id` INT UNSIGNED DEFAULT NULL,
  `tour_title` VARCHAR(255) NOT NULL,
  `tour_link` VARCHAR(255) DEFAULT NULL,
  `tour_image` VARCHAR(255) DEFAULT NULL,
  `departure_label` VARCHAR(255) DEFAULT NULL,
  `duration_label` VARCHAR(255) DEFAULT NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  `customer_email` VARCHAR(255) NOT NULL,
  `customer_phone` VARCHAR(50) NOT NULL,
  `customer_note` TEXT DEFAULT NULL,
  `adult_quantity` INT NOT NULL DEFAULT 1,
  `child_quantity` INT NOT NULL DEFAULT 0,
  `infant_quantity` INT NOT NULL DEFAULT 0,
  `adult_price` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `child_price` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `infant_price` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `grand_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'VND',
  `payment_method` VARCHAR(30) DEFAULT NULL,
  `payment_plan` ENUM('full','deposit') NOT NULL DEFAULT 'deposit',
  `payment_status` ENUM('draft','pending_payment','pending_transfer','paid','cancelled','failed') NOT NULL DEFAULT 'draft',
  `amount_due_vnd` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `amount_paid_vnd` DECIMAL(12,2) DEFAULT NULL,
  `paypal_order_id` VARCHAR(100) DEFAULT NULL,
  `paypal_capture_id` VARCHAR(100) DEFAULT NULL,
  `paypal_status` VARCHAR(50) DEFAULT NULL,
  `provider_reference` VARCHAR(100) DEFAULT NULL,
  `provider_payload` LONGTEXT DEFAULT NULL,
  `paid_at` DATETIME DEFAULT NULL,
  `cancelled_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_bookings_booking_code` (`booking_code`),
  UNIQUE KEY `uq_bookings_paypal_order_id` (`paypal_order_id`),
  KEY `idx_bookings_user_id` (`user_id`),
  KEY `idx_bookings_tour_id` (`tour_id`),
  KEY `idx_bookings_payment_status` (`payment_status`),
  KEY `idx_bookings_created_at` (`created_at`),
  CONSTRAINT `fk_bookings_user_id`
    FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

