<?php
// Editorial destination introductions; factual reference: vietnam.travel/places-to-go.
return [
    'Ha Long Bay' => [
        ['A landscape shaped by water and stone', 'Limestone towers rise from the sea in layered silhouettes, with small coves and passages appearing as you move through the bay. Ha Long is a landscape best understood from the water: the same islands can look dramatic beneath clouds and almost delicate in the evening light. Spending time on deck is as much a part of the experience as the stops along the way.'],
        ['Beyond the view from the deck', 'Cave visits reveal another side of the limestone landscape, with chambers and rock formations hidden inside the islands. A kayak or small boat brings the cliffs closer and gives a different sense of their scale. These experiences depend on the cruise route, so choosing a journey is also about choosing how you want to explore.'],
        ['Life on the bay', 'Fishing communities are part of the story of Ha Long. Where a route includes a community visit, it offers context for the boats and everyday activity seen across the water. An overnight stay adds quieter moments: a changing sunset, dinner on board and the first light between the islands.'],
    ],
    'Hoi An' => [
        ['A trading town with many stories', 'Hoi An grew as a trading port, and its old houses, assembly halls and Japanese Covered Bridge reflect the cultures that met here. Behind the yellow façades are courtyards, carved timber and family histories. Walking slowly through the Ancient Town makes those details easier to notice than simply moving from one landmark to the next.'],
        ['From old streets to open countryside', 'The experience changes outside the centre. Small roads lead through rice fields and vegetable gardens towards the coast. Tra Que offers a connection to the herbs and produce used in local cooking, while An Bang brings a relaxed beach setting. This contrast gives Hoi An more variety than its famous evening streets alone suggest.'],
        ['Flavours and evenings by the river', 'Food is a natural way into the town: cao lau noodles and delicate white rose dumplings are local signatures. Workshops and tailoring add another layer of craft and creativity. As daylight fades, lanterns brighten the streets and the riverside becomes a place to wander, pause for dinner and enjoy the atmosphere.'],
    ],
    'Ninh Binh' => [
        ['Vietnam’s countryside, on a remarkable scale', 'In Ninh Binh, steep limestone hills rise directly from fields and waterways. Villages, temples and working farmland sit within the scenery, giving the area a lived-in character as well as dramatic views. It is a place where a quiet country road can be just as memorable as a famous lookout.'],
        ['Trang An, Tam Coc and the view from above', 'Boat journeys at Trang An and Tam Coc bring you close to the water, passing beneath cliffs and through caves. The pace is gentle, with the landscape gradually opening around each bend. Hang Mua offers a contrasting perspective: a steep stair climb leads to views across the surrounding fields, river and limestone peaks.'],
        ['An ancient capital among the hills', 'Hoa Lu connects this landscape to Vietnam’s early history as the site of a former capital. Its temples add a cultural dimension to a visit focused on nature. Around Tam Coc, cycling is another way to experience the countryside, leaving room to stop at a village, observe the fields or simply enjoy the changing light.'],
    ],
    'Phu Quoc' => [
        ['An island with more than beaches', 'Phu Quoc combines long stretches of coast with a green interior and a history tied to fishing and agriculture. Resort life is one part of the island, but pepper cultivation, fish sauce production and fishing communities give it a distinct identity. A visit can move easily between time by the sea and learning about what the island produces.'],
        ['Choose your own coastal rhythm', 'Long Beach is associated with west-coast sunsets, while other stretches of coastline offer different settings for a relaxed day. Boat excursions provide another perspective on the surrounding islands. Some travellers fill their days with activities; others leave the schedule open for a swim, a book and an unhurried meal.'],
        ['A taste of island life', 'Seafood, locally grown pepper and fish sauce connect the island’s food to its livelihoods. Visiting a producer gives familiar ingredients a new story. Phu Quoc works especially well as a change of pace within a longer journey, with time to enjoy the island beyond a single sightseeing stop.'],
    ],
    'Sapa' => [
        ['Terraces beneath the mountains', 'Sapa’s landscape unfolds in steep valleys, cultivated terraces and mountain ridges. The fields change with the farming seasons, so the view is never a fixed postcard. Mist can soften the hills, while clearer moments reveal the scale of the valley below the town and the high peaks beyond.'],
        ['Walking through the Muong Hoa Valley', 'A walk offers a closer connection to the landscape than a viewpoint alone. Paths pass fields, streams and settlements, with routes ranging from shorter outings to more demanding days. A local guide can explain how the land is farmed and introduce the communities and traditions that shape everyday life here.'],
        ['Culture and the high peaks', 'Sapa is home to different ethnic communities, with distinctive textiles, customs and craft traditions. Encounters are most meaningful when there is time for conversation and respect for daily life. Fansipan adds a different experience, with mountain scenery and religious architecture above the valley. Cloud and weather are part of the experience, so each visit can feel different.'],
    ],
    'Hanoi' => [
        ['A capital discovered at street level', 'Hanoi combines busy commercial streets with lakes, temples and quieter courtyards. In the Old Quarter, shopfronts, small cafés and street kitchens share the pavement with everyday city life. The pleasure of exploring is often in these contrasts: stepping from traffic and conversation into a peaceful interior just a few metres away.'],
        ['History woven into the city', 'Hoan Kiem Lake provides a familiar point of orientation, while the Temple of Literature introduces a different side of the capital’s cultural history. Museums and heritage sites offer context for the streets outside. Rather than treating the city as a quick arrival stop, allowing time to walk and look closely reveals how its different layers coexist.'],
        ['A city to taste and return to', 'A bowl of pho, grilled pork with noodles or a small cup of coffee can become a memorable part of a day here. Food stalls and cafés also create opportunities to pause and watch the neighbourhood. Hanoi rewards curiosity: an early walk and an evening outing can give entirely different impressions of the same street.'],
    ],
    'Da Nang' => [
        ['Where the city meets the sea', 'Da Nang has the energy of a growing city alongside a broad coastline. The beach is part of everyday life, with morning exercise, fishing activity and evening walks giving it a local rhythm. My Khe’s open shoreline makes the contrast with the streets behind it especially clear.'],
        ['Headlands, caves and coastal views', 'Son Tra Peninsula brings wooded hills and sea views close to the city. The Marble Mountains offer another change of scene, combining limestone formations, caves and places of worship. These landscapes make Da Nang a varied stop, with opportunities to move between the coast, cultural sites and the city rather than spending every day in the same setting.'],
        ['A base for Central Vietnam', 'Food and cafés are part of the city’s appeal, and the riverside gives evenings a different atmosphere from the beach. Da Nang can also connect with Hoi An and the route towards Hue. That makes it a useful place to combine coastal relaxation with a wider introduction to Central Vietnam’s heritage.'],
    ],
    'Da Lat' => [
        ['A different side of Vietnam', 'Da Lat’s highland setting gives it a character distinct from the tropical coast. Pine-covered hills, gardens and a central lake sit alongside villas, cafés and busy market streets. The atmosphere encourages slower exploration: a walk, a coffee stop and time to notice the landscape around the city.'],
        ['Gardens, farms and the surrounding hills', 'Flowers and farming are part of the area’s identity. Beyond the centre, countryside excursions introduce a landscape of cultivated slopes and green valleys. Coffee experiences can connect a familiar drink to the place it is grown, while walks offer a chance to enjoy the highland scenery at a more personal pace.'],
        ['City character and outdoor experiences', 'Da Lat also has playful architecture and reminders of its history as a hill station. Local markets bring a lively contrast to its quieter lakes and pine forests. It is this mix of city detail and surrounding nature that gives the destination depth, whether your interest is photography, food or simply a change of atmosphere.'],
    ],
    'Nha Trang' => [
        ['A coastal city facing an island-filled bay', 'Nha Trang combines a long urban beachfront with a bay dotted with islands. It has a lively holiday atmosphere, yet the sea remains the centre of the experience. A morning walk, a boat outing and a seafood dinner offer different ways to enjoy the same coastal setting.'],
        ['On the water and beyond the beach', 'Island excursions bring a change of perspective from the city shoreline, with activities depending on the route and sea conditions. Back on land, mud baths and mineral-water experiences add another option for a slower day. The appeal is the ability to mix time outdoors with time simply relaxing.'],
        ['Heritage beside the coast', 'The Po Nagar towers introduce Cham heritage and provide a cultural counterpoint to the beaches. Temples and neighbourhoods add further reasons to explore beyond the resort. Nha Trang suits a journey that leaves space for several moods: active time on the bay, an introduction to local history and an easy evening by the water.'],
    ],
];
