<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bộ sưu tập tour | Travel Plus</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="<?= esc(frontend_asset_url('assets/css/admin.css'),'attr') ?>" rel="stylesheet"></head>
<body class="bg-light"><main class="container py-5" style="max-width:1080px">
<a href="<?= site_url('admin/tours') ?>">← Quản lý tour</a><h1 class="h3 mt-4">Bộ sưu tập tour</h1><p class="text-secondary">Tạo mùa hoặc chiến dịch mới, sau đó chọn bộ sưu tập khi tạo/sửa tour. Một tour có thể thuộc nhiều bộ sưu tập.</p>
<?php foreach (['error'=>'danger','success'=>'success'] as $key=>$class): ?><?php if ($message=session()->getFlashdata($key)): ?><div role="status" class="alert alert-<?= $class ?>"><?= esc($message) ?></div><?php endif ?><?php endforeach ?>
<section class="card p-4 my-4"><h2 class="h5">Thêm bộ sưu tập</h2><form method="post" action="<?= site_url('admin/tour-collections') ?>"><?= csrf_field() ?><div class="row g-3 align-items-end"><div class="col-md-4"><label for="new-vi" class="form-label">Tên tiếng Việt</label><input id="new-vi" name="name_vi" required maxlength="150" class="form-control" placeholder="Ví dụ: Mùa đông, Tết, Hè" value="<?= esc(old('name_vi',''),'attr') ?>"></div><div class="col-md-4"><label for="new-en" class="form-label">Tên tiếng Anh</label><input id="new-en" name="name_en" maxlength="150" class="form-control" value="<?= esc(old('name_en',''),'attr') ?>"></div><div class="col-md-2"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked> Hiển thị</label></div><div class="col-md-2"><button class="btn btn-primary w-100">Thêm mới</button></div></div></form></section>
<h2 class="h5 mb-3">Các bộ sưu tập</h2>
<?php foreach ($collections as $item): $id=(int)$item['id']; ?>
<section class="card p-4 mb-3"><form method="post" action="<?= site_url('admin/tour-collections/'.$id) ?>"><?= csrf_field() ?><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label" for="vi-<?= $id ?>">Tên tiếng Việt</label><input id="vi-<?= $id ?>" name="name_vi" required maxlength="150" class="form-control" value="<?= esc($item['name_vi'],'attr') ?>"></div><div class="col-md-4"><label class="form-label" for="en-<?= $id ?>">Tên tiếng Anh</label><input id="en-<?= $id ?>" name="name_en" maxlength="150" class="form-control" value="<?= esc($item['name_en'],'attr') ?>"></div><div class="col-md-2"><label class="form-check"><input type="checkbox" class="form-check-input" name="is_active" value="1" <?= $item['is_active'] ? 'checked' : '' ?>> Hiển thị</label></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Lưu</button></div></div></form>
<div class="mt-3 small text-secondary">Mã: <?= esc($item['slug']) ?> · <a href="<?= esc(\App\Data\LocalizedPathCatalog::url('search','vi').'?'.http_build_query(['collection'=>$item['slug']]),'attr') ?>">Xem danh sách tour</a><?= $item['slug']==='mua-thu' ? ' · <a href="'.esc(site_url('tour-mua-thu'),'attr').'">Landing page mùa thu</a>' : '' ?></div></section>
<?php endforeach ?>
<p class="small text-secondary">Đổi tên không thay đổi đường dẫn bộ sưu tập. Bỏ chọn “Hiển thị” để tạm ẩn; các tour đã gán vẫn được giữ lại.</p>
</main></body></html>
